baseurl = "https://lizandconor.com/b9eecdc8f99a1bcb9207ba4de9566f75975a90a8/"
languageCode = "en-us"
title = "Liz & Conor's Wedding"
theme = "hugo-strata-theme"
# disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Liz & Conor's wedding website"
	description = "Victoria, BC, Canada - 27 April 2019"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add read time estimates in the format "X min read"
	show_read_time = false

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = ["css/main.css"]


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "beach_house.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "**Liz & Conor**"
		subbio = [
			"27 April 2019",
			"Victoria, BC, Canada"
			]
		# The icons will be shown if you enter your username
		twitter = ""
		github = ""
		gitlab = ""
		dribbble = ""
		facebook = ""
		googleplus = ""
		flickr = ""
		linkedin = ""

		copyright = [
			""
		]


	[params.about]
		hide  = false
		title = "Welcome"
		content = '<br> Welcome to our wedding website! We are getting married on 27 April 2019 in Victoria, BC, Canada. <br> <br> <iframe src="https://www.google.com/maps/d/embed?mid=1YTNMBcE8uDe74R4PHDETdcJE_7yyMOoy" width="100%" height="480"></iframe><br>'

	[params.portfolio]
		hide  = true
		title = "Gallery"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like

		[[params.portfolio.gallery]]
			image = "fulls/golfing.jpg"
			thumb = "thumbs/golfing.jpg"
			title = "Vancouver, 2018"
			description = ""

		[[params.portfolio.gallery]]
			image = "fulls/california.jpg"
			thumb = "thumbs/california.jpg"
			title = "California, 2017"
			description = ""

		[[params.portfolio.gallery]]
			image = "fulls/kylemore.jpg"
			thumb = "thumbs/kylemore.jpg"
			title = "Connemara, 2016"
			description = ""

		[[params.portfolio.gallery]]
			image = "fulls/sailing.jpg"
			thumb = "thumbs/sailing.jpg"
			title = "Vancouver Island, 2015"
			description = ""

		[[params.portfolio.gallery]]
			image = "fulls/liz_grad.jpg"
			thumb = "thumbs/liz_grad.jpg"
			title = "Oxford, 2014"
			description = ""

		[[params.portfolio.gallery]]
			image = "fulls/peroni.jpg"
			thumb = "thumbs/peroni.jpg"
			title = "Rome, 2013"
			description = ""

		[[params.portfolio.gallery]]
			image = "fulls/bruges.jpg"
			thumb = "thumbs/bruges.jpg"
			title = "Bruges, 2012"
			description = ""

		[[params.portfolio.gallery]]
			image = "fulls/punting.jpg"
			thumb = "thumbs/punting.jpg"
			title = "Oxford, 2011"
			description = ""

	[params.recentposts]
		hide  = true
		title = "Pages"

	[params.rss]
		hide = true

	[params.contact]
		hide  = true
		title = "Contact Us"
		content = "Use this form to say hello or ask questions and we'll email you back!"

		# This can be exact coordinates or a searchable address in google maps
		gmaps_address = ""
		address = [
		]
		# phone = ""

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "info@lizandconor.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"


# Menu links that appear on the left sidebar

[[menu.main]]
	name = "Events"
	url  = "events"
	weight = 1

[[menu.main]]
	name = "Getting Here"
	url  = "getting-here"
	weight = 2

[[menu.main]]
	name = "Things To Do"
	url  = "things-to-do"
	weight = 3

[[menu.main]]
	name = "Accommodation"
	url  = "accommodation"
	weight = 4

[[menu.main]]
	name = "Gallery"
	url  = "gallery"
	weight = 5

[[menu.main]]
	name = "Gifts"
	url  = "gifts"
	weight = 6

[[menu.main]]
	name = "Contact Us"
	url  = "contact"
	weight = 7
